GET http://localhost:3000/user

###

GET http://localhost:3000/user/admin

###

POST http://localhost:3000/user/
Content-Type: application/json

{
    "username": "admin",
    "password": "fi9hM@liki"
}

###

DELETE http://localhost:3000/user/admin

###

POST http://localhost:3000/user/login
Content-Type: application/json

{
    "username": "hakim",
    "password": "password"
}

###

